[2024-07-25T09:22:15.475+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_ids_ingest.get_id_from_json scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2024-07-25T09:22:15.518+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_ids_ingest.get_id_from_json scheduled__2023-04-04T00:00:00+00:00 [queued]>
[2024-07-25T09:22:15.519+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-07-25T09:22:15.587+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_id_from_json> on 2023-04-04 00:00:00+00:00
[2024-07-25T09:22:15.603+0000] {standard_task_runner.py:57} INFO - Started process 763 to run task
[2024-07-25T09:22:15.631+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple_ids_ingest', 'get_id_from_json', 'scheduled__2023-04-04T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/ids_ingest/ids_ingest_dag.py', '--cfg-path', '/tmp/tmpkgfvui8l']
[2024-07-25T09:22:15.674+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask get_id_from_json
[2024-07-25T09:22:15.948+0000] {task_command.py:416} INFO - Running <TaskInstance: simple_ids_ingest.get_id_from_json scheduled__2023-04-04T00:00:00+00:00 [running]> on host c7799c7b21e5
[2024-07-25T09:22:16.394+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajay' AIRFLOW_CTX_DAG_ID='simple_ids_ingest' AIRFLOW_CTX_TASK_ID='get_id_from_json' AIRFLOW_CTX_EXECUTION_DATE='2023-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-04T00:00:00+00:00'
[2024-07-25T09:22:16.396+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ids_ingest/ids_ingest_dag.py", line 19, in get_ids_from_json
    git = json.loads(f.read())
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-25T09:22:16.480+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple_ids_ingest, task_id=get_id_from_json, execution_date=20230404T000000, start_date=20240725T092215, end_date=20240725T092216
[2024-07-25T09:22:16.547+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task get_id_from_json (Expecting value: line 1 column 1 (char 0); 763)
[2024-07-25T09:22:16.635+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-25T09:22:16.670+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
